---
title: Mhaeussermann.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Manuel Häußermann
bio: Literatur, Kultur, Digitale Gesellschaft.
description: Ein Blog über Literatur und Kultur.
external-image: false
picture: assets/images/profile.jpg
resume: false
resume-external: true
resume-url: https://google.com/?q=my+resume
your url: http://mhaeussermann.github.io
permalink: "/:title/"
disqus:
  shortname: mydisqus
  categories: []
facebook: m.haeussermann
instagram: kanonenfutter
github: mhaeussermann
email: m.haeussermann@gmail.com
tinyletter: mhaeussermann
authors:
  mhaeussermann:
    name: Manuel Häußermann
    bio: Literaturwissenschaftler.
    external-image: false
    picture: assets/images/profile.jpg
    twitter: _mnjl
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true
dighum: true
about: true
blog: true
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true
animation: true
plugins:
- jekyll-seo-tag
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-admin
jekyll-mentions:
  base_url: https://github.com
exclude:
- travis.sh
- Rakefile
- README.md
- Gemfile
- Gemfile.lock
- FAQ.md
